num1 = eval(input("Please enter a number: \n"))
num2 = eval(input("Please enter another number: \n"))

print("The sum of",num1,"and",num2,"is",num1+num2)
print("The difference of",num1,"and",num2,"is",num1-num2)
print("The product of",num1,"and",num2, "is",num1*num2)
print("The quotient of",num1,"and",num2,"is",num1/num2)
print(num1,"exponent by",num2,"is",num1**num2)
print("The remainder of",num1,"and",num2,"is",num1%num2)
print("The floor division of",num1,"and",num2,"is",num1//num2)